databases:
  - name: photoalbum
    databaseName: photoalbum
    user: photoalbum_user

services:
  - type: web
    name: album
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: photoalbum
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false